INSERT INTO UTENTE(NAME, SURNAME) VALUES ('MARIO', 'ROSSI')

INSERT INTO REGIONE(NAME) VALUES ('Lazio')
INSERT INTO REGIONE(NAME) VALUES ('Piemonte')
INSERT INTO REGIONE(NAME) VALUES ('Toscana')
INSERT INTO REGIONE(NAME) VALUES ('Umbria')

INSERT INTO REGIONE_UTENTE(REGIONE_ID, UTENTE_ID) VALUES (1, 1)
INSERT INTO REGIONE_UTENTE(REGIONE_ID, UTENTE_ID) VALUES (2, 1)